### PR TITLE
Update contacts module

### LINKED ISSUE #3: Редагувати та видаляти записи з книги контактів; review функціонала
https://trello.com/c/MZlli7ZI/7-%D1%80%D0%B5%D0%B4%D0%B0%D0%B3%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D1%82%D0%B0-%D0%B2%D0%B8%D0%B4%D0%B0%D0%BB%D1%8F%D1%82%D0%B8-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8-%D0%B7-%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8-%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D1%96%D0%B2-review-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D1%96%D0%BE%D0%BD%D0%B0%D0%BB%D0%B0

### PR DESCRIPTION
**Pull request by Squidoo22**
- [x] takes everything related to contacts into a separate module
- [x] adds the ability to delete contacts from the address book

### CODE REVIEW

**Review by DmytroShirobokov92 — CHANGES_REQUESTED** [review]
need to update branch related changes in develop and resolve conflicts

**Comment by Squidoo22** [comment]
> need to update branch related changes in develop and resolve conflicts

Done✅

**Review by DmytroShirobokov92 — APPROVED** [review]
Looks good, thx

**Review by GolovskoyNickolay — APPROVED** [review]

**Comment by DmytroShirobokov92** [comment]
@Squidoo22 2 approvals ready, you can megre this PR

**Pull request merged**
